auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
schema_config:
  configs:
    - from: 2022-06-06
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
storage_config:
  tsdb:
    dir: /logs/loki/tsdb
    wal:
      enabled: true
      compression: true
  filesystem:
    directory: /logs/loki/chunks
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
compactor:
  working_directory: /logs/loki/compactor
  shared_store: filesystem
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 2
